[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pgsql",
  "php82Extensions.mbstring",
  "php82Extensions.xml",
  "php82Extensions.curl",
  "php82Extensions.gd",
  "php82Extensions.zip",
  "php82Extensions.intl",
  "php82Extensions.bcmath",
  "composer_2"
]

# Desactivamos la fase de Node completamente
[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = []

[start]
cmd = "php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=$PORT"